# Group by Product Category and find total revenue generated by each.

import pandas as pd

df = pd.read_csv('sales_data.csv')
total_revenue = df.groupby('Product Category')['Total Revenue'].sum()
print(total_revenue)

#OUTPUT
# Product Category
# Beauty Products     2621.90
# Books               1861.93
# Clothing            8128.93
# Electronics        34982.41
# Home Appliances    18646.16
# Sports             14326.52
# Name: Total Revenue, dtype: float64
